version: '2'
services:
  jenkinsmaster:
    build:
      context: ./image
    links:
       - smtpserver
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       # These MUST be the same directory otherwise these types of problems hit you
       # when running containers in jenkins in containers
       # https://damnhandy.com/2016/03/06/creating-containerized-build-environments-with-the-jenkins-pipeline-plugin-and-docker-well-almost/
       - /var/jenkins_home:/var/jenkins_home
       - ./hudson.tasks.Mailer.xml:/var/jenkins_home/hudson.tasks.Mailer.xml
       - ./credentials.xml:/var/jenkins_home/credentials.xml
       - ./gitkey.pem:/var/jenkins/gitkey.pem:ro
    image: jenkins-pipeline
    ports:
    - 8080:8080
    environment:
      JENKINS_HOME: /var/jenkins_home
      JAVA_OPTS : -Djenkins.install.runSetupWizard=false
      DOCKER_REG: https://${DOCKER_BASE}
      DOCKER_REG_CRED_ID: gituser
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_DEFAULT_REGION}
  smtpserver:
    labels:
    - traefik.enable=false
    image: namshi/smtp
